trigger:
- main

pool:
   vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: npx playwright test
  displayName: 'Run Playwright tests'
  workingDirectory: $(System.DefaultWorkingDirectory)/tests
  env:
    CI: 'true'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/test-results
    artifact: playwright-report
    publishLocation: 'pipeline'
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    searchFolder: $(System.DefaultWorkingDirectory)/test-results
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit-results.xml'
    mergeTestResults: true
    testRunTitle: 'Playwright Demo Tests'
  condition: succeededOrFailed() 